services:
    temporal:
        image: temporalio/auto-setup:latest
        extra_hosts:
          - "host.docker.internal:host-gateway"
        environment:
          DB: postgres12
          DB_PORT: 5432
          POSTGRES_USER: nil
          POSTGRES_PWD: Nilkamal09
          POSTGRES_SEEDS: host.docker.internal
          DYNAMIC_CONFIG_FILE_PATH: /etc/temporal/config/dynamicConfig/development-sql.yaml
        ports:
            - "7233:7233"
        volumes:
          - ./temporal/dynamicConfig:/etc/temporal/config/dynamicConfig

    temporal-ui: 
        image: temporalio/ui:latest
        depends_on:
          - temporal
        environment:
          TEMPORAL_ADDRESS: temporal:7233
          TEMPORAL_CORS_ORIGIN: http://localhost:3000,http://localhost:5173
        ports:
            - "8080:8080"
    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "8025:8025" # web 
        - "1025:1025" #smtp