apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: event-scheduler
type: Opaque
stringData:
  # Azure Managed PostgreSQL
  DATABASE_URL: "postgresql://pgadmin:Nilkamal09.@event-scheduler-22536.postgres.database.azure.com:5432/event-scheduler?sslmode=require"
  
  # Temporal Persistence & Visibility on Azure PostgreSQL
  TEMPORAL_DB_URL: "postgresql://pgadmin:Nilkamal09.@event-scheduler-22536.postgres.database.azure.com:5432/temporal?sslmode=require"
  TEMPORAL_VISIBILITY_DB_URL: "postgresql://pgadmin:Nilkamal09.@event-scheduler-22536.postgres.database.azure.com:5432/temporal_visibility?sslmode=require"

  # Google OAuth & Calendar
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_REFRESH_TOKEN: ""

  # SMTP Credentials
  SMTP_USER: ""
  SMTP_PASSWORD: ""
